2019-10-18 16:28:35,919 ERROR: Exception on /about [GET] [in e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Google_Drive\3.Projects\0.LUAN_VAN\Embedded_Code\seperate_components\saveInfoServer\app\routes.py", line 30, in about
    return render_template('about.html')
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "E:\Google_Drive\3.Projects\0.LUAN_VAN\Embedded_Code\seperate_components\saveInfoServer\app\templates\about.html", line 2, in top-level template code
    {% from "_formhelper.html" import render_button %}
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "E:\Google_Drive\3.Projects\0.LUAN_VAN\Embedded_Code\seperate_components\saveInfoServer\app\templates\about.html", line 21, in root
    </p>
  File "E:\Google_Drive\3.Projects\0.LUAN_VAN\Embedded_Code\seperate_components\saveInfoServer\app\templates\base.html", line 14, in root
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block_doc
    {% block body -%}
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 39, in block_html
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 92, in block_body
  File "E:\Google_Drive\3.Projects\0.LUAN_VAN\Embedded_Code\seperate_components\saveInfoServer\app\templates\base.html", line 32, in block_content
  File "E:\Google_Drive\3.Projects\0.LUAN_VAN\Embedded_Code\seperate_components\saveInfoServer\app\templates\about.html", line 31, in block_app_content
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-10-18 16:30:02,319 ERROR: Exception on /about [GET] [in e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Google_Drive\3.Projects\0.LUAN_VAN\Embedded_Code\seperate_components\saveInfoServer\app\routes.py", line 33, in about
    return render_template('about.html')
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "E:\Google_Drive\3.Projects\0.LUAN_VAN\Embedded_Code\seperate_components\saveInfoServer\app\templates\about.html", line 2, in top-level template code
    {% from "_formhelper.html" import render_button %}
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "E:\Google_Drive\3.Projects\0.LUAN_VAN\Embedded_Code\seperate_components\saveInfoServer\app\templates\about.html", line 21, in root
    </p>
  File "E:\Google_Drive\3.Projects\0.LUAN_VAN\Embedded_Code\seperate_components\saveInfoServer\app\templates\base.html", line 14, in root
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block_doc
    {% block body -%}
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 39, in block_html
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 92, in block_body
  File "E:\Google_Drive\3.Projects\0.LUAN_VAN\Embedded_Code\seperate_components\saveInfoServer\app\templates\base.html", line 32, in block_content
  File "E:\Google_Drive\3.Projects\0.LUAN_VAN\Embedded_Code\seperate_components\saveInfoServer\app\templates\about.html", line 31, in block_app_content
  File "e:\google_drive\3.projects\0.luan_van\embedded_code\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
